### PR TITLE
adding zt

### PR DESCRIPTION
**Pull request by wesreisz**

### CODE REVIEW

**Comment by wesreisz** [comment]
> Build failed because of:
> bad indentation of a sequence entry at line 362, column 12:
> - item:
> ^
Fixing

**Comment by dankohn** [comment]
@wesreisz It's important not to merge PRs until you see that they have successfully built. Please don't break master for everyone else.

**Comment by wesreisz** [comment]
@dankohn Apologies. Just ran into some drift from the commits to landscape.yml. I thought I had resolved them using the github ui and missed the duplicates. When you're attempting to add 100s of logos to the landscape, waiting 5-10 minutes for a complete build for each one is pretty disruptive. No excuse, I should have caught it. I'll be more diligent. Apologies for the impact.

**Comment by dankohn** [comment]
I’m happy to help set you up to build locally in which the feedback loop drops from 5 mins to 5 secs. Just ping me on Slack. 

--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
dankohn.com or book on my calendar: dankohn.com/c

**Pull request merged**
